version: "3.6"

services:
    mongo:
        image: mongo:latest
        environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
        ports:
            - 27017:27017
    database_client:
        image: adminer
        restart: always
        ports:
            - 8080:8080